pull_request_rules:
  - name: "Auto-Merge Security Updates (dependabot[bot])"
    conditions:
      - author=dependabot[bot]
    actions:
      merge:
        method: merge

  - name: "Auto-Merge Security Updates (dependabot-preview[bot])"
    conditions:
      - author=dependabot-preview[bot]
    actions:
      merge:
        method: merge
